services:
  api:
    image: node:24
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3005:3000'
    restart: unless-stopped
