# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    env:
      NODE_ENV: development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          cp .env.sample .env
          mysql -u root -proot < db/create-db.sql
      - name: Use Node.js ${{ matrix.node-version }} in ${{ env.NODE_ENV }} mode
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
      - name: Generate API documentation
        run: npm run apidoc
      - name: Upload API documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: apidoc-node-${{ matrix.node-version }}
          path: ./apidoc/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/node/ciharkka
            docker-compose down
            git pull origin main
            npm install
            npm run test
            npm run apidoc
            docker-compose up -d --build
